### PR TITLE
feat: github app get access token for an installation given org

### PR DESCRIPTION
**Pull request by sqin2019**
rest api doc: https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-organization-installation-for-the-authenticated-app

required by https://github.com/abcxyz/team-link/issues/24

### CODE REVIEW

**Review by sethvargo — COMMENTED** [review]
Hi @sqin2019 - can you link to the GitHub documentation for this? I'm not sure I like overloading the `githubAccessToken` function like this.

**Comment by sqin2019** [comment]
> Hi @sqin2019 - can you link to the GitHub documentation for this? I'm not sure I like overloading the `githubAccessToken` function like this.

Do you mean this [link](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-organization-installation-for-the-authenticated-app)? 

Let me clarify a little bit more: 

- Goal - To be able to get an access token for a GitHub app installation that is installed on an different org.
- Step added in the `githubAccessToken` - get the app installation ID for that org (instead of the one in the *App object) and then use that ID to generate the access token.

Here are what I tried:
1. get the installation ID outside of this package - some of the code (`AppToken`) overlaps with this package. 
2. make `githubAccessToken` generic and can get any response given different GitHub request - essentially the same as this PR.

Do you have any suggestions?

**Comment by sethvargo** [comment]
> Goal - To be able to get an access token for a GitHub app installation that is installed on an different org.

The installation ID is a globally unique string. As long as you have the installation ID, everything should just work. Are you seeing something different?

**Comment by sqin2019** [comment]
> > Goal - To be able to get an access token for a GitHub app installation that is installed on an different org.
> 
> The installation ID is a globally unique string. As long as you have the installation ID, everything should just work. Are you seeing something different?

ah, I thought we can install the same private github app in different organizations if under the same enterprise, but it seems that a private github app is restricted to it's own org? I wonder what teamsync did as I don't see them using a github app per org.

**Comment by sethvargo** [comment]
> Update - seems can easily share the same github app across orgs by making it public in the github enterprise cloud account, or by https://docs.github.com/en/apps/sharing-github-apps/making-your-github-app-available-for-github-enterprise-server if it is a enterprise server account.

Ah yes - annoyingly GitHub Apps are either "private" (only available in your org) or "public" (visible to the entire Internet); there is no option to selectively expose. So yes, we'd have to make the GitHub App public to use it outside of our organization.

**Comment by sqin2019** [comment]
> > Update - seems can easily share the same github app across orgs by making it public in the github enterprise cloud account, or by https://docs.github.com/en/apps/sharing-github-apps/making-your-github-app-available-for-github-enterprise-server if it is a enterprise server account.
> 
> Ah yes - annoyingly GitHub Apps are either "private" (only available in your org) or "public" (visible to the entire Internet); there is no option to selectively expose. So yes, we'd have to make the GitHub App public to use it outside of our organization.

This githubauth package is designed for a single github app installation, should we make it support other installations too?

**Comment by sethvargo** [comment]
I'm not sure what you mean?

**Comment by sqin2019** [comment]
see https://github.com/abcxyz/pkg/pull/330

**Pull request closed without merging**
